[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_project = "BcsgHu3sCQkC5DfMjbqM74zJEdtY4m3ZfDqMVjGYeWcU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/philson_imac/.config/solana/id.json"

[scripts]
test = "node tests/anchor-project.js"
