[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_project = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/philson_imac/.config/solana/id.json"

[scripts]
test = "node tests/anchor-project.js"
